### ISSUE TITLE
Issue alert button not showing

### ISSUE THREAD

**Issue by frommberger** [waidyanatha/mobileSAMBRO#42]
The "issue new alert" button might be not showing, even if the user has the needed permissions.

**Comment by anggabayu21** [comment]
the reason is not showing is because the user doesn't have a role match with the editor or approval.
the app will get role value from this url "http://sambro.geoinfo.ait.ac.th/eden/default/index/user_info"
the output of the url is a json, 
for example : 
{
 r: ["a"],
 pid: 27, uid: 12, o: 2
}
r is a role and value a is a approval.

for admin@example.com the role is empty

**Comment by frommberger** [comment]
So the app is correct and just the roles for admin@example.com are set to the wrong values?

**Comment by anggabayu21** [comment]
this is the screenshoot from the user admin@example.com
![screen shot 2016-05-29 at 8 36 34 am](https://cloud.githubusercontent.com/assets/16677809/15698500/875d76b4-27ef-11e6-8190-611c212d91e0.png)

**Comment by biplovbhandari** [comment]
On Wed, Jun 1, 2016 at 12:19 AM, Lutz notifications@github.com wrote:

> So the app is correct and just the roles for admin@example.com are set to
> the wrong values?

not the wrong values. those are intended!
ᐧ
